/*
 * config.h
 *
 *  Created on: Nov 27, 2024
 *      Author: mvm
 */

#ifndef THEODOLITE_PERIPHERAL_CPU_BOARD_CONFIG_CONFIG_H_
#define THEODOLITE_PERIPHERAL_CPU_BOARD_CONFIG_CONFIG_H_

#include "lwip/debug.h"

#define ENC_NETIF_DEBUG           LWIP_DBG_OFF
#define NETIF_DEBUG_WARNING (ENC_NETIF_DEBUG | LWIP_DBG_LEVEL_WARNING)
#define NETIF_DEBUG_TRACE (ENC_NETIF_DEBUG | LWIP_DBG_LEVEL_ALL)
#define NETIF_DEBUGF LWIP_DEBUGF
#define NETIF_ASSERT LWIP_ASSERT

#define FOC_DEBUG           LWIP_DBG_ON
#define FOC_DEBUG_SERIOUS (FOC_DEBUG | LWIP_DBG_LEVEL_SERIOUS)
#define FOC_DEBUG_WARNING (FOC_DEBUG | LWIP_DBG_LEVEL_WARNING)
#define FOC_DEBUG_TRACE (FOC_DEBUG | LWIP_DBG_LEVEL_ALL)
#define FOC_DEBUGF LWIP_DEBUGF
#define FOC_ASSERT LWIP_ASSERT


#endif /* THEODOLITE_PERIPHERAL_CPU_BOARD_CONFIG_CONFIG_H_ */
